version: '3.7'

networks:
  dashy-net:
    driver: bridge

services:
  prometheus:
    container_name: dashy_prometheus
    image: prom/prometheus:v2.41.0
    hostname: prometheus
    restart: always
    networks:
      - dashy-net
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./deployment/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=10y'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    container_name: dashy_grafana
    image: grafana/grafana:9.3.2
    hostname: grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
    networks:
      - dashy-net
    depends_on:
      - prometheus
    volumes:
      - ./deployment/grafana_data:/var/lib/grafana
      - ./config/grafana/:/etc/grafana/provisioning/
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini

  api:
    container_name: dashy_api
    image: dashy-api:local
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    volumes:
      - ./deployment/api_data/data.db:/usr/src/data.db
    networks:
      - dashy-net
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  frontend:
    container_name: dashy_frontend
    image: dashy-frontend:local
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    restart: always
    ports:
      - 2015:80
    networks:
      - dashy-net
    depends_on:
      - api

  loki:
    image: grafana/loki:2.7.1
    command: -config.file=/etc/loki/config.yaml
    restart: always
    networks:
      - dashy-net
    ports:
      - 3100:3100
    volumes:
      - ./config/loki/config.yaml:/etc/loki/config.yaml
      - ./deployment/loki/wal:/wal

  promtail:
    image: grafana/promtail:2.6.1
    command: -config.file=/etc/promtail/config.yaml
    restart: always
    networks:
      - dashy-net
    volumes:
      - ./config/promtail/config.yaml:/etc/promtail/config.yaml
      # - /var/run/docker.sock:/var/run/docker.sock
      # - ./logs:/var/log/repo
