version: '3.7'

networks:
  dashy-net:
    driver: bridge

services:
  docker-exporter:
    container_name: dashy_docker-exporter
    image: prometheusnet/docker_exporter:latest
    restart: always
    networks:
      - dashy-net
    depends_on:
      - prometheus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prometheus:
    container_name: dashy_prometheus
    image: prom/prometheus:v2.31.1
    hostname: prometheus
    restart: always
    networks:
      - dashy-net
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./deployment/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=10y'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    container_name: dashy_grafana
    image: grafana/grafana:8.5.15
    hostname: grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
    networks:
      - dashy-net
    depends_on:
      - prometheus
    volumes:
      - ./deployment/grafana_data:/var/lib/grafana
      - ./config/grafana/:/etc/grafana/provisioning/
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini

  api:
    container_name: dashy_api
    image: dashy-api:local
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    volumes:
      - ./deployment/api_data/tools.json:/usr/src/tools.json
      - ./deployment/api_data/backups.json:/usr/src/backups.json
    networks:
      - dashy-net
    ports:
      - 3333:3333
    depends_on:
      - prometheus

  frontend:
    container_name: dashy_frontend
    image: dashy-frontend:local
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    restart: always
    ports:
      - 2015:80
    networks:
      - dashy-net
    depends_on:
      - api

  backup:
    container_name: dashy_backup
    image: dashy-backup:local
    build:
      context: .
      dockerfile: apps/backup/Dockerfile
    restart: always
    ports:
      - 3334:3334
    volumes:
      - ./deployment/backup_data:/usr/src/data
